apiVersion: apps/v1
Kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: database
          image: vrushyash/mariadb:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: mysql123
            - name: MYSQL_DATABASE
              value: testDB
            - name: MYSQL_USER
              value: vrushal
            - name: MYSQL_PASSWORD
              value: mysql123
          volumeMounts:
          - name: DB
            mountPath: /var/lib/mysql
      volumes:
      - name: mysql-db-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
    