apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
spec:
  selector:
    matchLabels:
      app: tomcat
  replicas: 2
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: vrushyash/tomcat:latest
        resources:
          limits:
            memory: "100Mi"
            cpu: "50m"
        ports:
        - containerPort: 8080
        env:
          - name: MYSQL_SERVER_HOST
            value: database
          - name: MYSQL_SERVER_PORT
            value: 3306
          - name: MYSQL_SERVER_DB_NAME
            value: testDB
          - name: MYSQL_SERVER_USER
            value: vrushal
          - name: MYSQL_SERVER_PASSWORD
            value: mysql123
          
